/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedSidebarRouteImport } from './routes/_protected/_sidebar'
import { Route as ProtectedSidebarTransactionsRouteImport } from './routes/_protected/_sidebar.transactions'
import { Route as ProtectedSidebarSettingsRouteImport } from './routes/_protected/_sidebar.settings'
import { Route as ProtectedSidebarInventoryRouteImport } from './routes/_protected/_sidebar.inventory'
import { Route as ProtectedSidebarDashboardRouteImport } from './routes/_protected/_sidebar.dashboard'
import { Route as ProtectedSidebarCustomersRouteImport } from './routes/_protected/_sidebar.customers'
import { Route as ProtectedSidebarSalesNewRouteImport } from './routes/_protected/_sidebar.sales.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSidebarRoute = ProtectedSidebarRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSidebarTransactionsRoute =
  ProtectedSidebarTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)
const ProtectedSidebarSettingsRoute =
  ProtectedSidebarSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)
const ProtectedSidebarInventoryRoute =
  ProtectedSidebarInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)
const ProtectedSidebarDashboardRoute =
  ProtectedSidebarDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)
const ProtectedSidebarCustomersRoute =
  ProtectedSidebarCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)
const ProtectedSidebarSalesNewRoute =
  ProtectedSidebarSalesNewRouteImport.update({
    id: '/sales/new',
    path: '/sales/new',
    getParentRoute: () => ProtectedSidebarRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/customers': typeof ProtectedSidebarCustomersRoute
  '/dashboard': typeof ProtectedSidebarDashboardRoute
  '/inventory': typeof ProtectedSidebarInventoryRoute
  '/settings': typeof ProtectedSidebarSettingsRoute
  '/transactions': typeof ProtectedSidebarTransactionsRoute
  '/sales/new': typeof ProtectedSidebarSalesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/customers': typeof ProtectedSidebarCustomersRoute
  '/dashboard': typeof ProtectedSidebarDashboardRoute
  '/inventory': typeof ProtectedSidebarInventoryRoute
  '/settings': typeof ProtectedSidebarSettingsRoute
  '/transactions': typeof ProtectedSidebarTransactionsRoute
  '/sales/new': typeof ProtectedSidebarSalesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/_sidebar': typeof ProtectedSidebarRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/_sidebar/customers': typeof ProtectedSidebarCustomersRoute
  '/_protected/_sidebar/dashboard': typeof ProtectedSidebarDashboardRoute
  '/_protected/_sidebar/inventory': typeof ProtectedSidebarInventoryRoute
  '/_protected/_sidebar/settings': typeof ProtectedSidebarSettingsRoute
  '/_protected/_sidebar/transactions': typeof ProtectedSidebarTransactionsRoute
  '/_protected/_sidebar/sales/new': typeof ProtectedSidebarSalesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/settings'
    | '/transactions'
    | '/sales/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/settings'
    | '/transactions'
    | '/sales/new'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/login'
    | '/_protected/_sidebar'
    | '/_protected/onboarding'
    | '/_protected/_sidebar/customers'
    | '/_protected/_sidebar/dashboard'
    | '/_protected/_sidebar/inventory'
    | '/_protected/_sidebar/settings'
    | '/_protected/_sidebar/transactions'
    | '/_protected/_sidebar/sales/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_sidebar': {
      id: '/_protected/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedSidebarRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_sidebar/transactions': {
      id: '/_protected/_sidebar/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ProtectedSidebarTransactionsRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
    '/_protected/_sidebar/settings': {
      id: '/_protected/_sidebar/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSidebarSettingsRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
    '/_protected/_sidebar/inventory': {
      id: '/_protected/_sidebar/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof ProtectedSidebarInventoryRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
    '/_protected/_sidebar/dashboard': {
      id: '/_protected/_sidebar/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedSidebarDashboardRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
    '/_protected/_sidebar/customers': {
      id: '/_protected/_sidebar/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedSidebarCustomersRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
    '/_protected/_sidebar/sales/new': {
      id: '/_protected/_sidebar/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof ProtectedSidebarSalesNewRouteImport
      parentRoute: typeof ProtectedSidebarRoute
    }
  }
}

interface ProtectedSidebarRouteChildren {
  ProtectedSidebarCustomersRoute: typeof ProtectedSidebarCustomersRoute
  ProtectedSidebarDashboardRoute: typeof ProtectedSidebarDashboardRoute
  ProtectedSidebarInventoryRoute: typeof ProtectedSidebarInventoryRoute
  ProtectedSidebarSettingsRoute: typeof ProtectedSidebarSettingsRoute
  ProtectedSidebarTransactionsRoute: typeof ProtectedSidebarTransactionsRoute
  ProtectedSidebarSalesNewRoute: typeof ProtectedSidebarSalesNewRoute
}

const ProtectedSidebarRouteChildren: ProtectedSidebarRouteChildren = {
  ProtectedSidebarCustomersRoute: ProtectedSidebarCustomersRoute,
  ProtectedSidebarDashboardRoute: ProtectedSidebarDashboardRoute,
  ProtectedSidebarInventoryRoute: ProtectedSidebarInventoryRoute,
  ProtectedSidebarSettingsRoute: ProtectedSidebarSettingsRoute,
  ProtectedSidebarTransactionsRoute: ProtectedSidebarTransactionsRoute,
  ProtectedSidebarSalesNewRoute: ProtectedSidebarSalesNewRoute,
}

const ProtectedSidebarRouteWithChildren =
  ProtectedSidebarRoute._addFileChildren(ProtectedSidebarRouteChildren)

interface ProtectedRouteChildren {
  ProtectedSidebarRoute: typeof ProtectedSidebarRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedSidebarRoute: ProtectedSidebarRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
